version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i_s
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.ginx
    container_name: server
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"

